SELECT SYSTIMESTAMP
     , EXTRACT(YEAR FROM SYSTIMESTAMP) AS 년도
     , EXTRACT(MONTH FROM SYSTIMESTAMP) AS 월
     , EXTRACT(DAY FROM SYSTIMESTAMP) AS 일
     , EXTRACT(HOUR FROM SYSTIMESTAMP) AS 시간
     , EXTRACT(MINUTE FROM SYSTIMESTAMP) AS 분
     , EXTRACT(SECOND FROM SYSTIMESTAMP) AS 초
FROM DUAL;