SELECT MEM_NO
  	, ORDER_DATE
	, SALES_QTY
     ,COUNT(ORDER_NO) OVER (PARTITION BY MEM_NO ORDER BY ORDER_DATE) AS 누적_구매횟수        
     ,SUM(SALES_QTY)  OVER (PARTITION BY MEM_NO ORDER BY ORDER_DATE) AS 누적_구매수량
     ,AVG(SALES_QTY)  OVER (PARTITION BY MEM_NO ORDER BY ORDER_DATE) AS 누적_평균구매수량
     ,MAX(SALES_QTY)  OVER (PARTITION BY MEM_NO ORDER BY ORDER_DATE) AS 누적_가장높은구매수량
     ,MIN(SALES_QTY)  OVER (PARTITION BY MEM_NO ORDER BY ORDER_DATE) AS 누적_가장낮은구매수량       
  FROM  Sales